FROM golang:1.25-alpine

WORKDIR /app

ENV GOPROXY=https://goproxy.cn,direct
ENV GOMODCACHE=/go/pkg/mod

RUN go install github.com/air-verse/air@latest && \
    apk add --no-cache curl

# Expose port
EXPOSE 10020

# Run air for hot reload
CMD ["air", "-c", ".air.toml"]
